In [ ]:
import pandas as pd
import numpy as np
import re

## 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

- Defining a list of country codes and using a for-loop to iterate through them.
- For each country, reading the corresponding CSV file and immediately tagging it by adding a new 'country' column.
- Finally, collecting all the dataframes and concatenating them into a single dataset

In [ ]:
country = ['CA', 'DE', 'FR', 'GB', 'IN', 'JP', 'KR', 'MX', 'RU', 'US']
list_total = []
for c in country:
    path = '/Users/asiarubini/Desktop/UNI/DATA SCIENCE/COMPUTER SCIENCE/PROJECT FOCS/trendingYT/' + c + 'videos.csv'
    df = pd.read_csv(path, encoding_errors='replace')
    df['country'] = c
    list_total.append(df)

df_total = pd.concat(list_total, ignore_index=True)
df_total

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

## 2. Extract all videos that have no tag.

Checking whether there are Nan values

In [ ]:
df_total['tags'].isnull().sum()

np.int64(0)

There are not --> checking how many tags are '[none]'

In [ ]:
(df_total['tags'] == '[none]').sum()

np.int64(37698)

Since it is not 0, we can extract lines having tags equal to [none]

In [ ]:
none_tags_df = df_total[df_total['tags'] == '[none]']
none_tags_df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
41,JwboxqDylgg,17.14.11,Canada Soccer's Women's National Team v USA In...,Canada Soccer,17,2017-11-13T05:53:49.000Z,[none],36311,277,28,13,https://i.ytimg.com/vi/JwboxqDylgg/default.jpg,False,False,False,Canada Soccer's Women's National Team face riv...,CA
58,9B-q8h31Bpk,17.14.11,John Oliver Tackles Louis C.K. And Donald Trum...,TV Shows,22,2017-11-13T04:49:26.000Z,[none],106029,1270,101,181,https://i.ytimg.com/vi/9B-q8h31Bpk/default.jpg,False,False,False,"John Oliver on News, Politics ...",CA
78,1UE5Dq1rvUA,17.14.11,Taylor Swift Perform Ready For It - SNL,Ken Reactz,24,2017-11-12T05:18:02.000Z,[none],320964,8069,285,717,https://i.ytimg.com/vi/1UE5Dq1rvUA/default.jpg,False,False,False,Thanks for watching please subscribe and subsc...,CA
86,pmJQ4KwliX4,17.14.11,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",James Munder,2,2017-11-12T21:25:40.000Z,[none],116820,1503,139,1066,https://i.ytimg.com/vi/pmJQ4KwliX4/default.jpg,False,False,False,https://pastebin.ca/3930472\n\nSupport My Chan...,CA
98,lHcXhBojpeQ,17.14.11,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,明星百曉生,22,2017-11-12T12:49:50.000Z,[none],88061,47,58,17,https://i.ytimg.com/vi/lHcXhBojpeQ/default.jpg,False,False,False,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375815,VGykknw9eCM,18.14.06,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...",Beats by Dre,10,2018-06-07T07:01:06.000Z,[none],3577614,12318,1345,1414,https://i.ytimg.com/vi/VGykknw9eCM/default.jpg,False,False,False,"When your time comes, you have two choices. Yo...",US
375819,fAIX12F6958,18.14.06,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05T07:00:01.000Z,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,US
375865,gS1DbvHHVH0,18.14.06,Going in to brain surgery,Simone Giertz,28,2018-05-30T14:22:13.000Z,[none],1635301,120791,1098,20711,https://i.ytimg.com/vi/gS1DbvHHVH0/default.jpg,False,False,False,We’ll post an update on Instagram and Twitter ...,US
375873,E4c7EE8_IX0,18.14.06,Weezer - Africa,weezer,10,2018-05-29T12:00:11.000Z,[none],4682557,115240,5069,9170,https://i.ytimg.com/vi/E4c7EE8_IX0/default.jpg,False,False,False,Stream + download the song: http://fanlink.to/...,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US

## 3. For each channel, determine the total number of views

In [ ]:
df_total.groupby('channel_title')['views'].sum().reset_index().sort_values(by='views', ascending=False)

              channel_title        views
4564    ChildishGambinoVEVO  11016766510
15536  Marvel Entertainment  10430605449
17726            NickyJamTV   9479859505
18466                 Ozuna   8623329509
28412               ibighit   8205572221
...                     ...          ...
17437     NavylittleMonster          365
25828      Videostendencias          302
17837         No Comment TV          284
22560            Sport Life          163
1370      Alexander Redking          153

[37824 rows x 2 columns]

## 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

Determining the number of videos with comments disabled, ratings disabled, and those flagged as video error or removed

In [ ]:
int((df_total['comments_disabled'] == True).sum())

8463

In [ ]:
int((df_total['ratings_disabled'] == True).sum())

7308

In [ ]:
int((df_total['video_error_or_removed'] == True).sum())

253

Creating a new dataframe called excluded filtering all the rows with disabled comments/ratings or videos with errors or removed (using the & and | operators)

In [ ]:
excluded = df_total[
    (df_total['comments_disabled'] == True) & (df_total['ratings_disabled'] == True) |
    (df_total['video_error_or_removed'] == True)
]

In [ ]:
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
173,H8IWLEtFt9A,17.14.11,Intégrale - On n'est pas couché 11 novembre 20...,On n'est pas couché,24,2017-11-12T01:44:07.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",122282,0,0,0,https://i.ytimg.com/vi/H8IWLEtFt9A/default.jpg,True,True,False,Intégrale - On n'est pas couché 11 novembre 20...,CA
1069,om-_yJaSW_Y,17.19.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",523258,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1278,om-_yJaSW_Y,17.20.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1004809,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1320,faJOpxEyTWk,17.20.11,Intégrale - On n'est pas couché 18 novembre 20...,On n'est pas couché,24,2017-11-19T02:01:15.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",87544,0,0,0,https://i.ytimg.com/vi/faJOpxEyTWk/default.jpg,True,True,False,Intégrale - On n'est pas couché 18 novembre 20...,CA
1573,om-_yJaSW_Y,17.21.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1197269,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368180,1Aoc-cd9eYs,18.07.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",672609,4916,197,1269,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368407,1Aoc-cd9eYs,18.08.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",412323,25441,208,952,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368613,1Aoc-cd9eYs,18.09.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",251857,6623,231,1120,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368830,1Aoc-cd9eYs,18.10.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",629055,30695,277,1033,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
369587,1Aoc-cd9eYs,18.14.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",1062499,32276,4594,5547,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US

Saving in a new dataframe all the videos which are not in excluded

In [ ]:
df_total_noexcluded = df_total[~df_total.index.isin(excluded.index)].copy()
df_total_noexcluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

## 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [ ]:
df_total_noexcluded['like_ratio'] = df_total_noexcluded['likes']/df_total_noexcluded['dislikes']
df_total_noexcluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US,27.552347
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US,157.089005
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US,46.577519
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799368
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616

## 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

Checking the format of the values in the 'publish_time' column.

In [ ]:
df_total_noexcluded['publish_time']

0         2017-11-10T17:00:03.000Z
1         2017-11-13T17:00:00.000Z
2         2017-11-12T19:05:24.000Z
3         2017-11-12T18:01:41.000Z
4         2017-11-09T11:04:14.000Z
                    ...
375937    2018-05-18T13:00:04.000Z
375938    2018-05-18T01:00:06.000Z
375939    2018-05-18T17:34:22.000Z
375940    2018-05-17T17:00:04.000Z
375941    2018-05-17T17:09:38.000Z
Name: publish_time, Length: 373322, dtype: object

Since the values are strings, it needs to transform their format into datetime64 format

In [ ]:
df_total_noexcluded['publish_time'] = pd.to_datetime(df_total_noexcluded['publish_time'])
df_total_noexcluded['publish_time']

0        2017-11-10 17:00:03+00:00
1        2017-11-13 17:00:00+00:00
2        2017-11-12 19:05:24+00:00
3        2017-11-12 18:01:41+00:00
4        2017-11-09 11:04:14+00:00
                    ...
375937   2018-05-18 13:00:04+00:00
375938   2018-05-18 01:00:06+00:00
375939   2018-05-18 17:34:22+00:00
375940   2018-05-17 17:00:04+00:00
375941   2018-05-17 17:09:38+00:00
Name: publish_time, Length: 373322, dtype: datetime64[ns, UTC]

- Rounding the publish_time down to 10-minute intervals
- extracting only the time component, removing the specific date

In [ ]:
start_time = df_total_noexcluded['publish_time'].dt.floor('10min')
end_time = start_time + pd.Timedelta(minutes=10)
df_total_noexcluded['publish_interval_10min'] = ('from' + start_time.dt.strftime('%H:%M') + 'to' + end_time.dt.strftime('%H:%M'))

In [ ]:
df_total_noexcluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346,from 17:00 to 17:10
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500,from 19:00 to 19:10
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168,from 18:00 to 18:10
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,from 11:00 to 11:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US,27.552347,from 13:00 to 13:10
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US,157.089005,from 01:00 to 01:10
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US,46.577519,from 17:30 to 17:40
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,from 17:00 to 17:10
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,from 17:00 to 17:10

## 7. For each interval, determine the number of videos, average number of likes and of dislikes.

In [ ]:
df_intervals = df_total_noexcluded.groupby('publish_interval_10min').agg(
    n_videos=('video_id', 'count'),
    avg_likes=('likes', 'mean'),
    avg_dislikes=('dislikes', 'mean')
)
df_intervals

                        n_videos     avg_likes  avg_dislikes
publish_interval_10min
from 00:00 to 00:10         2897  61288.115637   3808.149465
from 00:10 to 00:20         1509  22748.138502   1449.836315
from 00:20 to 00:30         1241  21378.280419   1072.344883
from 00:30 to 00:40         1614  36853.560719    955.890954
from 00:40 to 00:50         1269  42198.623325   1909.301812
...                          ...           ...           ...
from 23:10 to 23:20         1554  22783.840412   1110.168597
from 23:20 to 23:30         1438  30696.510431   1177.020862
from 23:30 to 23:40         1666  18159.173469    874.184874
from 23:40 to 23:50         1466  45736.581855   9341.549795
from 23:50 to 00:00         1269  10853.743893    505.701340

[144 rows x 3 columns]

## 8. For each tag, determine the number of videos
Notice that tags contains a string with several tags.

Checking, randomly, the format of the values in 'tags'

In [ ]:
df_total_noexcluded['tags'].sample()

52955    VFB Stuttgart|"Hertha berlin SC"|"Stuttgart vs...
Name: tags, dtype: object

Creating a new dataframe with all the videos which have real tags (not '[none]')

In [ ]:
df_tags = df_total_noexcluded[~(df_total_noexcluded['tags'] == '[none]')].copy()

In [ ]:
df_tags

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346,from 17:00 to 17:10
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500,from 19:00 to 19:10
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168,from 18:00 to 18:10
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,from 11:00 to 11:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375936,1PhPYr_9zRY,18.14.06,BTS Plays With Puppies While Answering Fan Que...,BuzzFeed Celeb,22,2018-05-18 16:39:29+00:00,"BuzzFeed|""BuzzFeedVideo""|""Puppy Interview""|""pu...",8259128,645888,4052,62610,https://i.ytimg.com/vi/1PhPYr_9zRY/default.jpg,False,False,False,"BTS with the PPS, the puppies. These adorable ...",US,159.399803,from 16:30 to 16:40
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US,27.552347,from 13:00 to 13:10
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US,46.577519,from 17:30 to 17:40
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,from 17:00 to 17:10
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,from 17:00 to 17:10

Cleaning the column 'tags': how?
- creating a new column 'tags_cleaned' with tags values without any special characters

In [ ]:
df_tags["tags_cleaned"] = df_tags["tags"].str.replace(r'[\[\]\"]', '', regex=True)

- Transforming each concatenated string in 'tags_cleaned' into a list of tags saved in a new column called 'tags_splitted'

In [ ]:
df_tags["tags_splitted"] = df_tags["tags_cleaned"].str.split('|')
df_tags

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min,tags_cleaned,tags_splitted
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10,Eminem|Walk|On|Water|Aftermath/Shady/Interscop...,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte..."
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346,from 17:00 to 17:10,plush|bad unboxing|unboxing|fan mail|idubbbztv...,"[plush, bad unboxing, unboxing, fan mail, idub..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,...,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500,from 19:00 to 19:10,racist superman|rudy|mancuso|king|bach|racist|...,"[racist superman, rudy, mancuso, king, bach, r..."
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,...,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168,from 18:00 to 18:10,ryan|higa|higatv|nigahiga|i dare you|idy|rhpc|...,"[ryan, higa, higatv, nigahiga, i dare you, idy..."
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,from 11:00 to 11:10,edsheeran|ed sheeran|acoustic|live|cover|offic...,"[edsheeran, ed sheeran, acoustic, live, cover,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375936,1PhPYr_9zRY,18.14.06,BTS Plays With Puppies While Answering Fan Que...,BuzzFeed Celeb,22,2018-05-18 16:39:29+00:00,"BuzzFeed|""BuzzFeedVideo""|""Puppy Interview""|""pu...",8259128,645888,4052,...,https://i.ytimg.com/vi/1PhPYr_9zRY/default.jpg,False,False,False,"BTS with the PPS, the puppies. These adorable ...",US,159.399803,from 16:30 to 16:40,BuzzFeed|BuzzFeedVideo|Puppy Interview|puppy|j...,"[BuzzFeed, BuzzFeedVideo, Puppy Interview, pup..."
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,...,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US,27.552347,from 13:00 to 13:10,aarons animals|aarons|animals|cat|cats|kitten|...,"[aarons animals, aarons, animals, cat, cats, k..."
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,...,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US,46.577519,from 17:30 to 17:40,I gave safiya nygaard a perfect hair makeover ...,[I gave safiya nygaard a perfect hair makeover...
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,...,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,from 17:00 to 17:10,Black Panther|HISHE|Marvel|Infinity War|How It...,"[Black Panther, HISHE, Marvel, Infinity War, H..."
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,from 17:00 to 17:10,call of duty|cod|activision|Black Ops 4,"[call of duty, cod, activision, Black Ops 4]"

Expanding each n-list into n-rows. Each row, in the column 'tags_splitted', will have a single tag value

In [ ]:
df_tags_exploded = df_tags.explode("tags_splitted").copy()
df_tags_exploded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min,tags_cleaned,tags_splitted
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10,Eminem|Walk|On|Water|Aftermath/Shady/Interscop...,Eminem
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10,Eminem|Walk|On|Water|Aftermath/Shady/Interscop...,Walk
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10,Eminem|Walk|On|Water|Aftermath/Shady/Interscop...,On
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10,Eminem|Walk|On|Water|Aftermath/Shady/Interscop...,Water
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10,Eminem|Walk|On|Water|Aftermath/Shady/Interscop...,Aftermath/Shady/Interscope
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,...,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,from 17:00 to 17:10,Black Panther|HISHE|Marvel|Infinity War|How It...,ending explained
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,from 17:00 to 17:10,call of duty|cod|activision|Black Ops 4,call of duty
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,from 17:00 to 17:10,call of duty|cod|activision|Black Ops 4,cod
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,from 17:00 to 17:10,call of duty|cod|activision|Black Ops 4,activision
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,from 17:00 to 17:10,call of duty|cod|activision|Black Ops 4,Black Ops 4

After cleaned the tags with white spaces inside, or empty tags or [none] tags, determining the number of videos for each tag

In [ ]:
df_tags_exploded = df_tags_exploded[(df_tags_exploded['tags_splitted'] != '[none]') & (df_tags_exploded['tags_splitted'] != '')]

In [ ]:
df_tags_exploded.groupby('tags_splitted')['video_id'].count().sort_values(ascending=False)

tags_splitted
funny                           15039
comedy                          12351
2018                            11371
news                             6363
music                            5909
                                ...
infidélité dans le couple           1
infidélité amoureuse                1
infidèle peut devenir fidèle        1
infidelidad por dinero              1
🤝 ZARBEX zahlt Schutzgeld!!!        1
Name: video_id, Length: 849277, dtype: int64

## 9. Find the tags with the largest number of videos

In [ ]:
df_tags_exploded.groupby('tags_splitted')['video_id'].count().sort_values(ascending = False).head(10)

tags_splitted
funny         15039
comedy        12351
2018          11371
news           6363
music          5909
2017           5688
video          5612
humor          5057
television     4170
show           4146
Name: video_id, dtype: int64

In this case, we do not use .idxmax() because it would return only a single tag (the one with the absolute highest value). Point 9 requires us to identify all tags with the maximum number of videos

In [ ]:
# df_tags_exploded.groupby('tags_split')['video_id'].count().idxmax()

## 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [ ]:
df_tags_exploded.groupby(['tags_splitted','country'])['like_ratio'].mean()

tags_splitted                                    country
 #Freeticket                                     IN          2.665679
 #GST                                            IN          2.416896
 #Jaisimha                                       IN          2.665679
 #JanaSenaParty                                  IN         17.621907
 #MahaaNews                                      IN          8.511947
                                                              ...
😥                                                DE         26.384615
😭 #résistancelamaindesqueezie ❤️                 FR         10.219048
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية  FR          6.223873
🚀 smartpixel.com.ua                              RU          0.714286
🤝 ZARBEX zahlt Schutzgeld!!!                     DE         13.989691
Name: like_ratio, Length: 1098601, dtype: float64

## 11. For each (trending_date, country) pair, the video with the largest number of views

In [ ]:
df_total_noexcluded.loc[df_total_noexcluded.groupby(['trending_date','country'])['views'].idxmax()]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min
3398,6ZfuNTqbHE8,17.01.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",56367282,2157741,34078,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...,CA,63.317712,from 13:20 to 13:30
44280,6ZfuNTqbHE8,17.01.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",56367282,2157737,34077,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...,DE,63.319453,from 13:20 to 13:30
85252,3VbHg5fqBYw,17.01.12,Avengers: Infinity War Trailer Tease,Marvel Entertainment,24,2017-11-28 17:09:22+00:00,"marvel""|""comics""|""comic books""|""nerdy""|""geeky""...",7281189,180808,19955,21244,https://i.ytimg.com/vi/3VbHg5fqBYw/default.jpg,False,False,False,Thank you to the best fans in the universe! Ma...,FR,9.060787,from 17:00 to 17:10
126032,TyHvyGVs42U,17.01.12,"Luis Fonsi, Demi Lovato - Échame La Culpa",LuisFonsiVEVO,10,2017-11-17 05:00:01+00:00,"Luis|""Fonsi""|""Demi""|""Lovato""|""Échame""|""La""|""Cu...",143408235,2686169,137938,144217,https://i.ytimg.com/vi/TyHvyGVs42U/default.jpg,False,False,False,“Échame La Culpa” disponible ya en todas las p...,GB,19.473742,from 05:00 to 05:10
164617,6ZfuNTqbHE8,17.01.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29 13:26:24+00:00,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",56367282,2157733,34077,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...,IN,63.319336,from 13:20 to 13:30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216792,aJOTlE1K90k,18.31.05,Maroon 5 - Girls Like You ft. Cardi B,Maroon5VEVO,10,2018-05-31 04:00:00+00:00,"Maroon|""Girls""|""Like""|""You""|""Interscope""|""Reco...",3057987,406732,4521,31301,https://i.ytimg.com/vi/aJOTlE1K90k/default.jpg,False,False,False,Girls Like You” is out now.http://smarturl.it/...,JP,89.965052,from 04:00 to 04:10
251198,ntWSnDV0MYs,18.31.05,[MV] AOA _ Bingle Bangle(빙글뱅글),1theK (원더케이),10,2018-05-28 09:00:03+00:00,"Kpop|""1theK""|""원더케이""|""loen""|""로엔""|""뮤비""|""티져""|""MV""...",4150448,186262,9728,15989,https://i.ytimg.com/vi/ntWSnDV0MYs/default.jpg,False,False,False,[MV] AOA _ Bingle Bangle(빙글뱅글)*English subtitl...,KR,19.146998,from 09:00 to 09:10
291483,xTlNMmZKwpA,18.31.05,"Cardi B, Bad Bunny & J Balvin - I Like It [Off...",Cardi B,10,2018-05-29 14:05:10+00:00,"Cardi B|""I Like It""|""Invasion of Privacy""|""Bad...",20723565,1018817,48091,68790,https://i.ytimg.com/vi/xTlNMmZKwpA/default.jpg,False,False,False,"Cardi B, Bad Bunny & J Balvin - I Like It from...",MX,21.185191,from 14:00 to 14:10
332058,1nX0kF2UwDc,18.31.05,[BadComedian] - Движение Вверх (Плагиат или ве...,BadComedian,23,2018-05-30 18:20:48+00:00,"BadComedian|""Евген""|""Bad""|""Comedian""|""Фильмы""|...",3125598,334685,7777,34556,https://i.ytimg.com/vi/1nX0kF2UwDc/default.jpg,False,False,False,"#BadComedian обзор фильма Движение Вверх, кото...",RU,43.035232,from 18:20 to 18:30
373139,VYOjWnS4cMY,18.31.05,Childish Gambino - This Is America (Official V...,ChildishGambinoVEVO,10,2018-05-06 04:00:07+00:00,"Childish Gambino|""Rap""|""This Is America""|""mcDJ...",217750076,4934188,335462,509799,https://i.ytimg.com/vi/VYOjWnS4cMY/default.jpg,False,False,False,“This is America” by Childish Gambino http://s...,US,14.708635,from 04:00 to 04:10

## 12. Divide trending_date into three columns: year, month, day

Checking the 'trending_date' format

In [ ]:
df_total_noexcluded['trending_date']

0         17.14.11
1         17.14.11
2         17.14.11
3         17.14.11
4         17.14.11
            ...
375937    18.14.06
375938    18.14.06
375939    18.14.06
375940    18.14.06
375941    18.14.06
Name: trending_date, Length: 373322, dtype: object

Converting the column to datetime. The format '%y.%d.%m' tells Python to parse the date structure as Year.Day.Month.

In [ ]:
df_total_noexcluded['trending_date_dt'] = pd.to_datetime(df_total_noexcluded['trending_date'], format='%y.%d.%m')

Creating the three columns

In [ ]:
df_total_noexcluded['year'] = df_total_noexcluded['trending_date_dt'].dt.year
df_total_noexcluded['month'] = df_total_noexcluded['trending_date_dt'].dt.month
df_total_noexcluded['day'] = df_total_noexcluded['trending_date_dt'].dt.day
df_total_noexcluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min,trending_date_dt,year,month,day
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10,2017-11-14,2017,11,14
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,False,False,STill got a lot of packages. Probably will las...,CA,75.707346,from 17:00 to 17:10,2017-11-14,2017,11,14
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,...,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.352500,from 19:00 to 19:10,2017-11-14,2017,11,14
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,...,False,False,I know it's been a while since we did this sho...,CA,66.485168,from 18:00 to 18:10,2017-11-14,2017,11,14
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,from 11:00 to 11:10,2017-11-14,2017,11,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,...,False,False,The Cat Who Caught the Laser - Aaron's Animals,US,27.552347,from 13:00 to 13:10,2018-06-14,2018,6,14
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,...,False,False,NaN,US,157.089005,from 01:00 to 01:10,2018-06-14,2018,6,14
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,...,False,False,I had so much fun transforming Safiyas hair in...,US,46.577519,from 17:30 to 17:40,2018-06-14,2018,6,14
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,...,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,from 17:00 to 17:10,2018-06-14,2018,6,14
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,from 17:00 to 17:10,2018-06-14,2018,6,14

## 13. For each (month, country) pair, the video with the largest number of views

In [ ]:
df_total_noexcluded.loc[df_total_noexcluded.groupby(['month','country'])['views'].idxmax()]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min,trending_date_dt,year,month,day
11214,LsoLEjrDogU,18.09.01,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04 04:49:43+00:00,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",43067983,1717177,61567,...,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,CA,27.891192,from 04:40 to 04:50,2018-01-09,2018,1,9
51930,LsoLEjrDogU,18.08.01,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04 04:49:43+00:00,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",37728802,1629946,56305,...,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,DE,28.948513,from 04:40 to 04:50,2018-01-08,2018,1,8
92853,LsoLEjrDogU,18.08.01,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04 04:49:43+00:00,"Bruno Mars""|""Finesse""|""Cardi B""|""Finesse Remix...",37728802,1629948,56305,...,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,FR,28.948548,from 04:40 to 04:50,2018-01-08,2018,1,8
135208,LsoLEjrDogU,18.18.01,Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...,Bruno Mars,10,2018-01-04 04:49:43+00:00,"Bruno Mars|""Finesse""|""Cardi B""|""Finesse Remix""...",90598955,2248693,93089,...,False,False,Finesse (Remix) Feat. Cardi B Available Now: h...,GB,24.156377,from 04:40 to 04:50,2018-01-18,2018,1,18
173405,dfnCAmr569k,18.18.01,"Taylor Swift - End Game ft. Ed Sheeran, Future",TaylorSwiftVEVO,10,2018-01-12 05:00:01+00:00,"Taylor|""Swift""|""End""|""Game""|""Big""|""Machine""|""Pop""",42019590,1804377,100033,...,False,False,Music video by Taylor Swift performing End Gam...,IN,18.037818,from 05:00 to 05:10,2018-01-18,2018,1,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166769,FlsCjmMhFmw,17.12.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",125432237,2912710,1545017,...,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",IN,1.885228,from 17:50 to 18:00,2017-12-12,2017,12,12
224092,FlsCjmMhFmw,17.11.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",113876217,2811223,1470388,...,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",KR,1.911892,from 17:50 to 18:00,2017-12-11,2017,12,11
259064,FlsCjmMhFmw,17.10.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",100912384,2656698,1353667,...,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",MX,1.962593,from 17:50 to 18:00,2017-12-10,2017,12,10
299087,FlsCjmMhFmw,17.08.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",52611730,1891836,884967,...,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",RU,2.137748,from 17:50 to 18:00,2017-12-08,2017,12,8
341174,FlsCjmMhFmw,17.14.12,YouTube Rewind: The Shape of 2017 | #YouTubeRe...,YouTube Spotlight,24,2017-12-06 17:58:51+00:00,"Rewind|""Rewind 2017""|""youtube rewind 2017""|""#Y...",149376127,3093544,1643059,...,False,False,"YouTube Rewind 2017. Celebrating the videos, p...",US,1.882795,from 17:50 to 18:00,2017-12-14,2017,12,14

## 14. Read all json files with the video categories

In [ ]:
country = ['CA', 'DE', 'FR', 'GB', 'IN', 'JP', 'KR', 'MX', 'RU', 'US']
list_total_cat = []
for c in country:
    path = '/Users/asiarubini/Desktop/UNI/DATA SCIENCE/COMPUTER SCIENCE/PROJECT FOCS/trendingYT/' + c + '_category_id.json'
    df = pd.read_json(path, encoding_errors='replace')
    df_norm = pd.json_normalize(df['items'])
    df_norm['country'] = c
    df_norm['id'] = df_norm['id'].astype(int)
    list_total_cat.append(df_norm)

df_total_category = pd.concat(list_total_cat, ignore_index=True)
df_total_category

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,country
0,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,CA
1,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,CA
2,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,CA
3,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,CA
4,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,CA
...,...,...,...,...,...,...,...
306,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False,US
307,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False,US
308,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False,US
309,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False,US
310,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False,US

## 15. For each country, determine how many videos have a category that is not assignable.

Merging the two total dataframes on the columns 'country' and 'category_id'='id'

In [ ]:
merged_df = pd.merge(df_total_noexcluded, df_total_category, left_on=['country','category_id'], right_on=['country','id'], how='left')
merged_df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,trending_date_dt,year,month,day,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,...,2017-11-14,2017,11,14,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10.0,UCBR8-60-B28hp2BmDPdntcQ,Music,True
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,...,2017-11-14,2017,11,14,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/G9LHzQmx44rX2S5ya...",23.0,UCBR8-60-B28hp2BmDPdntcQ,Comedy,True
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,...,2017-11-14,2017,11,14,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/G9LHzQmx44rX2S5ya...",23.0,UCBR8-60-B28hp2BmDPdntcQ,Comedy,True
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,...,2017-11-14,2017,11,14,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UVB9oxX2Bvqa_w_y3...",24.0,UCBR8-60-B28hp2BmDPdntcQ,Entertainment,True
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,...,2017-11-14,2017,11,14,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10.0,UCBR8-60-B28hp2BmDPdntcQ,Music,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373317,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,...,2018-06-14,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/HwXKamM1Q20q9BN-o...",15.0,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True
373318,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[none],1064798,60008,382,...,2018-06-14,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/xId8RX7vRN8rqkbYZ...",22.0,UCBR8-60-B28hp2BmDPdntcQ,People & Blogs,True
373319,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,...,2018-06-14,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/UVB9oxX2Bvqa_w_y3...",24.0,UCBR8-60-B28hp2BmDPdntcQ,Entertainment,True
373320,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,...,2018-06-14,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/Xy1mB4_yLrHy_BmKm...",1.0,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True
373321,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,...,2018-06-14,2018,6,14,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/WmA0qYEfjWsAoyJFS...",20.0,UCBR8-60-B28hp2BmDPdntcQ,Gaming,True

Checking how many values of 'snippet.assignable' are Nan and how many are False (in this situation, it means the same thing)

In [ ]:
merged_df[merged_df['snippet.assignable'].isnull()]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,trending_date_dt,year,month,day,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable
43,0gLWN3uq74o,17.14.11,Ex-intelligence chiefs fire back at Trump crit...,CNN,29,2017-11-12 15:36:51+00:00,"James Clapper|""John Brennan""|""President Trump""...",286231,2530,1127,...,2017-11-14,2017,11,14,NaN,NaN,NaN,NaN,NaN,NaN
227,HnCU20Cu0fs,17.15.11,Dashcam Norway - Semi-truck narrowly missing kids,FBas,29,2017-11-15 07:37:18+00:00,"dashcam|""accident""|""traffic""|""safety""|""volvo""|...",2253298,4632,104,...,2017-11-15,2017,11,15,NaN,NaN,NaN,NaN,NaN,NaN
358,0gLWN3uq74o,17.15.11,Ex-intelligence chiefs fire back at Trump crit...,CNN,29,2017-11-12 15:36:51+00:00,"James Clapper|""John Brennan""|""President Trump""...",311936,2627,1196,...,2017-11-15,2017,11,15,NaN,NaN,NaN,NaN,NaN,NaN
384,ClwBTkLiivk,17.15.11,Week 4 Challenge: Check out “My Email Leads”,CREA | ACI,29,2017-11-13 13:46:37+00:00,CREA,1898,0,0,...,2017-11-15,2017,11,15,NaN,NaN,NaN,NaN,NaN,NaN
488,HnCU20Cu0fs,17.16.11,ORIGINAL: Dashcam Norway - Semi truck narrowly...,Transferd AS,29,2017-11-15 07:37:18+00:00,"dashcam|""accident""|""traffic""|""safety""|""volvo""|...",2510664,0,0,...,2017-11-16,2017,11,16,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332366,6cMkFpzYJag,18.14.06,Пусть говорят. За больничной дверью: народные ...,Пусть говорят,29,2018-06-13 20:21:41+00:00,"Семья|""Общество""|""Шоу-бизнес""|""Дмитрий Борисов...",38740,226,119,...,2018-06-14,2018,6,14,NaN,NaN,NaN,NaN,NaN,NaN
332375,niKln6fWWrY,18.14.06,The Youth Board Asks #1 – How Does The Report ...,Supercell,29,2018-06-13 10:33:56+00:00,[none],640996,10105,1034,...,2018-06-14,2018,6,14,NaN,NaN,NaN,NaN,NaN,NaN
332424,tyFiwbR0aSI,18.14.06,Абрикосовое варенье без варки ягод цыганка гот...,Галина Кухня,29,2018-06-13 07:00:04+00:00,"варенье|""абрикосовое варенье""|""варень без варк...",37974,3701,41,...,2018-06-14,2018,6,14,NaN,NaN,NaN,NaN,NaN,NaN
332432,mjNw0tUlObQ,18.14.06,"УТЕЧКА: Тайный сговор, правительства и единоро...",Аксиома,29,2018-06-13 00:03:55+00:00,"правительство|""ндфл""|""экономика""|""налоги""|""акц...",78361,3189,1207,...,2018-06-14,2018,6,14,NaN,NaN,NaN,NaN,NaN,NaN
332501,Ehy5foVfKOE,18.14.06,Плохой сигнал. Стань человеком!,Tubus Show,29,2018-06-13 09:50:09+00:00,"плохой сигнал|""тубус шоу""|""reebok""|""стань чело...",52340,7708,133,...,2018-06-14,2018,6,14,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
merged_df[merged_df['snippet.assignable'] == False]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,trending_date_dt,year,month,day,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable
263,AlrbKKGIcjI,17.15.11,"Deivamagal Episode 1388, 14/11/17",VikatanTV,43,2017-11-14 15:00:00+00:00,"deivamagal|""deiva magal""|""deiva magal serial""|...",591632,3231,1327,...,2017-11-15,2017,11,15,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
348,mQbsY2KTFHk,17.15.11,"Слуга Народа 2 - От любви до импичмента, 22 се...",Слуга народа,43,2017-11-14 18:45:58+00:00,"сериал|""сериал 2017""|""сериал 4к""|""сериал слуга...",437979,8787,287,...,2017-11-15,2017,11,15,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
555,QfmIUoZej9Q,17.16.11,"Слуга Народа 2 - От любви до импичмента, 23 серия",Слуга народа,43,2017-11-15 18:42:55+00:00,"сериал|""сериал 2017""|""сериал 4к""|""сериал слуга...",467088,9228,220,...,2017-11-16,2017,11,16,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
680,5EBDXsTkg1E,17.17.11,"Priyamanaval Episode 866, 16/11/17",VikatanTV,43,2017-11-16 17:00:00+00:00,"Priyamanaval 16.11.2017|""priyamanaval 866""|""Pr...",416189,2107,714,...,2017-11-17,2017,11,17,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
772,xOjlzuWakD4,17.17.11,"Слуга Народа 2 - От любви до импичмента, 24 серия",Слуга народа,43,2017-11-16 18:48:38+00:00,"сериал|""сериал 2017""|""сериал 4к""|""сериал слуга...",487929,15866,378,...,2017-11-17,2017,11,17,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370905,V6ElE2xs48c,18.02.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1324482,22413,608,...,2018-06-02,2018,6,2,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
371108,V6ElE2xs48c,18.03.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1332252,22461,610,...,2018-06-03,2018,6,3,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
371312,V6ElE2xs48c,18.04.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1340039,22504,615,...,2018-06-04,2018,6,4,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
371514,V6ElE2xs48c,18.05.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1345086,22542,615,...,2018-06-05,2018,6,5,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
371717,V6ElE2xs48c,18.06.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1351321,22587,616,...,2018-06-06,2018,6,6,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False

Creating a new dataframe in which there are all videos with 'snippet.assignable' == False (--> 1015 videos) and all videos in which 'snippet.assignable' == Nan (it means that the category is not assignable, so it is considered as False --> 2684 videos)

In [ ]:
merged_df_false = merged_df[(merged_df['snippet.assignable'] == False) | (merged_df['snippet.assignable'].isnull())]
merged_df_false

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,trending_date_dt,year,month,day,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable
43,0gLWN3uq74o,17.14.11,Ex-intelligence chiefs fire back at Trump crit...,CNN,29,2017-11-12 15:36:51+00:00,"James Clapper|""John Brennan""|""President Trump""...",286231,2530,1127,...,2017-11-14,2017,11,14,NaN,NaN,NaN,NaN,NaN,NaN
227,HnCU20Cu0fs,17.15.11,Dashcam Norway - Semi-truck narrowly missing kids,FBas,29,2017-11-15 07:37:18+00:00,"dashcam|""accident""|""traffic""|""safety""|""volvo""|...",2253298,4632,104,...,2017-11-15,2017,11,15,NaN,NaN,NaN,NaN,NaN,NaN
263,AlrbKKGIcjI,17.15.11,"Deivamagal Episode 1388, 14/11/17",VikatanTV,43,2017-11-14 15:00:00+00:00,"deivamagal|""deiva magal""|""deiva magal serial""|...",591632,3231,1327,...,2017-11-15,2017,11,15,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
348,mQbsY2KTFHk,17.15.11,"Слуга Народа 2 - От любви до импичмента, 22 се...",Слуга народа,43,2017-11-14 18:45:58+00:00,"сериал|""сериал 2017""|""сериал 4к""|""сериал слуга...",437979,8787,287,...,2017-11-15,2017,11,15,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
358,0gLWN3uq74o,17.15.11,Ex-intelligence chiefs fire back at Trump crit...,CNN,29,2017-11-12 15:36:51+00:00,"James Clapper|""John Brennan""|""President Trump""...",311936,2627,1196,...,2017-11-15,2017,11,15,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370905,V6ElE2xs48c,18.02.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1324482,22413,608,...,2018-06-02,2018,6,2,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
371108,V6ElE2xs48c,18.03.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1332252,22461,610,...,2018-06-03,2018,6,3,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
371312,V6ElE2xs48c,18.04.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1340039,22504,615,...,2018-06-04,2018,6,4,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
371514,V6ElE2xs48c,18.05.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1345086,22542,615,...,2018-06-05,2018,6,5,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False
371717,V6ElE2xs48c,18.06.06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,"bleacher report|""br""|""nba""|""Stan Van Gundy""|""J...",1351321,22587,616,...,2018-06-06,2018,6,6,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43.0,UCBR8-60-B28hp2BmDPdntcQ,Shows,False

In [ ]:
merged_df_false.groupby('country', as_index=False)['video_id'].count().sort_values('video_id', ascending=False)

  country  video_id
8      RU      1733
6      KR       453
1      DE       352
4      IN       295
7      MX       254
2      FR       223
0      CA       204
3      GB       110
9      US        57
5      JP        18